apiVersion: ai.sap.com/v1alpha1
kind: Workflow
metadata:
  name: demo-workflow
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: busybox
        command: ["echo", "AI Core Integrated Successfully"]
