apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: your-workflow-name
  labels:
    ai.sap.com/scenario: your-scenario-name
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine
        command: ["echo"]
        args: ["Hello World"]
