apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-workflow
  labels:
    ai.sap.com/scenario: test-scenario
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine
        command: ["echo"]
        args: ["Hello World"]
